version: '3'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DBNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - './projeto:/var/lib/mysql'
